/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.3
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2019 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "LED_1.h"
#include "LED_1_aliases.h"
#include "CapSense_CSD.h"
#include "CapSense_CSD_CSHL.h"
#include "CapSense_CSD_TunerHelper.h"
#include "CapSense_CSD_PVT.h"
#include "CapSense_CSD_IP.h"
#include "Clock_PWM.h"
#include "LED_CONTROL.h"
#include "SW_Tx_UART_1.h"
#include "SW_Tx_UART_1_PVT.h"
#include "CapSense_CSD_SampleClk.h"
#include "CapSense_CSD_Sns_aliases.h"
#include "CapSense_CSD_SenseClk.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "cy_em_eeprom.h"
#include "CyLFClk.h"

/*[]*/

